# Generated by Django 5.1.2 on 2024-11-14 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seguridad_Privada',
            fields=[
                ('Id_Seguridad', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('contacto', models.IntegerField()),
                ('horarios', models.TimeField()),
                ('personal', models.IntegerField()),
                ('vehiculos', models.IntegerField()),
                ('servicios', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Seguridad Privada',
                'verbose_name_plural': 'Seguridad Privada',
                'db_table': 'Seguridad_Privada',
            },
        ),
    ]
